version: 0.0
os: linux

files:             
  - source: target/demo-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/

hooks:
  ApplicationStop:
   - location: ./codedeploy/applicationStop.sh
     timeout: 300
     runas: ec2-user
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 1200
      runas: ec2-user    
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 400
     runas: ec2-user
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 300
      runas: ec2-user

